### ISSUE TITLE
Improve code in VQE page

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/platypus#1224]
### Where does the issue happen?

https://learn.qiskit.org/course/ch-applications/simulating-molecules-using-vqe

### What is the content issue?

Thanks to #1188 the code in the VQE page now works correctly, but there are still places it can be improved.

- [ ] Neaten imports: The imports cell is huge, we might be able to import higher-level modules instead of importing each class individually, i.e. `import qiskit`, then use `qiskit.algorithms.optimizers.SLSQP(...)` in the main code. This will depend on how frequently we use each class.
- [ ] The functions have a lot of local variables, maybe we can reduce this or split into smaller functions.
- [ ] Need to add docstrings to functions.

**Comment by SamYuan1990** [comment]
Hi frank,
It seems repo https://github.com/anedumla/quantum_linear_solvers can't install directly by `pip install linear_solvers` hence, when I 
- checkout this repo
- find notebook for https://learn.qiskit.org/course/ch-applications/solving-linear-systems-of-equations-using-hhl-and-its-qiskit-implementation ...
- run notebook locally, my vscode reports error as `linear_solvers` module not found.

Hence, may I know if we can change the play book back to version https://qiskit.org/textbook/ch-applications/hhl_tutorial.html 
use 
```
from qiskit.algorithms.linear_solvers.numpy_linear_solver import NumPyLinearSolver
from qiskit.algorithms.linear_solvers.hhl import HHL
```

**Comment by frankharkins** [comment]
@SamYuan1990 did you mean to comment on this issue? This issue is for the VQE page, but you're asking about the HHL page.

You can install the package using

```
pip install git+https://github.com/anedumla/quantum_linear_solvers
```

I've made an issue to add these instructions to the page (https://github.com/Qiskit/platypus/issues/1786).

**Comment by SamYuan1990** [comment]
> ~@SamYuan1990 did you mean to comment on this issue? This issue is for the VQE page, but you're asking about the HHL page.~
> 
> EDIT: I see I pasted the wrong link in the original issue, I've corrected it now
> 
> You can install the package using
> 
> ```
> pip install git+https://github.com/anedumla/quantum_linear_solvers
> ```
> 
> I've made an issue to add these instructions to the page (#1786).

ok, I will check with VQE page. and thanks for information for #1786 :-)

**Comment by SamYuan1990** [comment]
hi frank,

I tried vscode with jupyter for VQE playbook. and I got blocked at running code block 
```
def exact_solver(problem, converter):
```
I am confused at `packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.`
full error log as below.
Please advise.

```
Visual Studio Code (1.74.2, undefined, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.1.
Workspace folder /Users/yuanyi/OpenSource/platypus
info 11:08:13.094: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 11:08:13.481: LSP Notebooks experiment is enabled
info 11:08:13.836: Find preferred kernel for /Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9"}} & preferred interpreter /opt/local/bin/python3.9
info 11:08:13.837: Find preferred kernel for /Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9"}} & preferred interpreter /opt/local/bin/python3.9
info 11:08:13.858: Find preferred kernel for /Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9"}} & preferred interpreter /opt/local/bin/python3.9
info 11:08:13.866: Find preferred kernel for /Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9"}} & preferred interpreter /opt/local/bin/python3.9
info 11:08:14.168: Got empty env vars with python /opt/local/bin/python3.9 in 327ms
info 11:08:14.170: Process Execution: > /opt/local/bin/python3.9 -m pip list
> /opt/local/bin/python3.9 -m pip list
info 11:08:15.263: Preferred kernel .jvsc74a57bd0f22a20af907fde35ff19e1e892fdb271353fb19b11c7ebd774491472e685293c./opt/local/bin/python3.9./opt/local/bin/python3.9.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 11:08:15.264: PreferredConnection: .jvsc74a57bd0f22a20af907fde35ff19e1e892fdb271353fb19b11c7ebd774491472e685293c./opt/local/bin/python3.9./opt/local/bin/python3.9.-m#ipykernel_launcher found for NotebookDocument: /Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb
info 11:08:16.188: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0f22a20af907fde35ff19e1e892fdb271353fb19b11c7ebd774491472e685293c./opt/local/bin/python3.9./opt/local/bin/python3.9.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.9.7 (default, Sep  1 2021, 04:00:27) 
[Clang 11.0.3 (clang-1103.0.32.62)]) for '/Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb' (disableUI=false)
info 11:08:16.189: Computing working directory for resource '/Users/yuanyi/OpenSource/platypus/notebooks/ch-applications/vqe-molecules.ipynb'
info 11:08:16.206: Process Execution: > /opt/local/bin/python3.9 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /opt/local/bin/python3.9 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 11:08:16.228: Process Execution: > /opt/local/bin/python3.9 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"16fe37ed-e02d-4d78-ae0c-a1670384e6b6" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/yuanyi/Library/Jupyter/runtime/kernel-v2-120501lun7TXWe8Ox.json
> /opt/local/bin/python3.9 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"16fe37ed-e02d-4d78-ae0c-a1670384e6b6" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/yuanyi/Library/Jupyter/runtime/kernel-v2-120501lun7TXWe8Ox.json
info 11:08:16.228: Process Execution: cwd: ~/OpenSource/platypus/notebooks/ch-applications
cwd: ~/OpenSource/platypus/notebooks/ch-applications
info 11:08:16.278: Got empty env vars with python /opt/local/bin/python3.9 in 83ms
info 11:08:16.278: Got empty env vars with python /opt/local/bin/python3.9 in 54ms
info 11:08:16.278: Got empty env vars with python /opt/local/bin/python3.9 in 53ms
info 11:08:16.557: ipykernel version & path 6.17.1, ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /opt/local/bin/python3.9
warn 11:08:17.244: StdErr from Kernel Process /Users/yuanyi/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 11:08:17.244: StdErr from Kernel Process /Users/yuanyi/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '16fe37ed-e02d-4d78-ae0c-a1670384e6b6' instead of 'b"16fe37ed-e02d-4d78-ae0c-a1670384e6b6"'.
  warn(

info 11:08:17.280: Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-120501lun7TXWe8Ox.json

info 11:08:17.464: Started Kernel Python 3.9.7 (pid: 12239)
info 11:08:17.466: UpdateWorkingDirectoryAndPath in Kernel
info 11:08:17.516: Process Execution: > /opt/local/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printJupyterDataDir.py
> /opt/local/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printJupyterDataDir.py
info 11:08:17.822: Got empty env vars with python /opt/local/bin/python3.9 in 315ms
error 11:08:22.107: Disposing session as kernel process died ExitCode: undefined, Reason: /Users/yuanyi/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/yuanyi/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '16fe37ed-e02d-4d78-ae0c-a1670384e6b6' instead of 'b"16fe37ed-e02d-4d78-ae0c-a1670384e6b6"'.
  warn(

info 11:08:22.108: Dispose Kernel process 12239.
error 11:08:22.109: Raw kernel process exited code: undefined
error 11:08:22.111: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:32353)
	at /Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:51405
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:51390)
	at y.dispose (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:44872)
	at /Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2184547
	at t.swallowExceptions (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:7:125449)
	at p.dispose (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2184525)
	at t.RawSession.dispose (/Users/yuanyi/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2189519)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 11:08:22.112: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 11:08:22.114: Cancel all remaining cells true || Error || undefined
```

**Comment by frankharkins** [comment]
I'm sorry I'm not sure, but my guess is this is a problem with vscode. Can you try installing everything through

```
cd platypus/converter/textbook-converter
pip install -r requirements.txt -r requirements-test.txt
```

if you haven't already? Or try using Jupyter notebook.

**Comment by SamYuan1990** [comment]
> I'm sorry I'm not sure, but my guess is this is a problem with vscode. Can you try installing everything through
> 
> ```
> cd platypus/converter/textbook-converter
> pip install -r requirements.txt -r requirements-test.txt
> ```
> 
> if you haven't already? Or try using Jupyter notebook.

it works now, thanks frank.
```
//$python is the python used in VS code for Jupyter notebook plugin.
$python -m  pip install -r requirements.txt -r requirements-test.txt
```

**Comment by pandasa123** [comment]
@frankharkins, if this is being refactored, is possible to use the `Sampler` for `Estimator` this body of work as well?
