### ISSUE TITLE
Platypus not deploying due to Vale configuration

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/platypus#1373]
There is some issue with Vale's configuration that is making the deployment workflow fail in the test step.

https://github.com/Qiskit/platypus/runs/7425210455?check_suite_focus=true#step:10:111

**Comment by eddybrando** [comment]
The issue seems to rely in this line: https://github.com/Qiskit/platypus/pull/1221/files#diff-535def396827d7f30a706b1babe813e76a96a36a717dfa759592c69a7ad72e12R80 introduced in https://github.com/Qiskit/platypus/pull/1221:

```python
 vale_result = subprocess.run(
        ['vale', path, '--output', 'JSON'],
        capture_output=True)
```

where `vale` can't be found and results in the error shown in https://github.com/Qiskit/platypus/runs/7425210455?check_suite_focus=true#step:10:111:

```
./notebooks/quantum-machine-learning/introduction.ipynb
Traceback (most recent call last):
  File "./scripts/content_checks/nb_vale.py", line 133, in <module>
    lint_notebook(filename, CI)
  File "./scripts/content_checks/nb_vale.py", line 53, in lint_notebook
    lint_markdown(outdir, CI)
  File "./scripts/content_checks/nb_vale.py", line 80, in lint_markdown
    vale_result = subprocess.run(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vale'
```
